name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why is this needed? What problem does it solve?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of omp does this relate to?
      options:
        - Provider / Model support
        - TUI / Display
        - Tools
        - MCP servers
        - Extensions / Plugins
        - CLI commands
        - Skills / Commands
        - Session management
        - Configuration
        - Other

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you implement this? Link to relevant docs or APIs if applicable.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or other approaches you've tried?
